### ISSUE TITLE
Invalid icon font file reference

### ISSUE THREAD

**Issue by thekaveman** [Office-of-Digital-Services/California-State-Web-Template-Website#493]
Hello there 👋 My team has been building the [Cal-ITP Benefits](https://github.com/cal-itp/benefits) application and have used a number of your assets (CSS, etc.) as the basis for our design. Thank you for sharing! 

We're in a Python/Django ecosystem and currently using `v6.0.2`; we point directly to your CDN-hosted assets. See e.g. [here in our main template file](https://github.com/cal-itp/benefits/blob/dev/benefits/core/templates/core/base.html#L18).

Recently we've started to look at upgrading to the more recent `v6.0.7`, and for a number of reasons, to inline the assets in our application rather than pointing to the CDN. I'll save you the long-winded steps that got us to find what seems to be a small bug/broken reference (you can read a little more background in cal-itp/benefits#777).

In [`source/scss/cagov/icon-font.scss`](https://github.com/Office-of-Digital-Services/California-State-Web-Template/blob/master/source/scss/cagov/icon-font.scss#L7) we can see a reference to an icon font file `ca-gov-icon.woff`:

```scss
@font-face {
  font-family: "CaGov";
  src: url("../fonts/CaGov.ttf?ocljyw") format("truetype"), url("fonts/ca-gov-icon.woff?t3czrh") format("woff"),
    url("../fonts/CaGov.woff2?ocljyw") format("woff2"), url("../fonts/CaGov.svg??ocljyw#CaGov") format("svg");
  font-weight: normal;
  font-style: normal;
  font-display: block;
}
```

This file seemingly does not exist anywhere in the repo; definitely not in a `fonts/` directory _inside_ the `source/scss/cagov/` directory, as indicated by the relative `url()` fragment above.

As best I can tell, #179 introduced this change, or perhaps ac0716e8a023d054362ea2c65092df09dda94793
